apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secrets
  namespace: laravel-local
type: Opaque
stringData:
  APP_KEY: "base64:9tDBD1l8cZkx3DLzI3VZ6c743teVfaVMBLP0WGQrmBA="
  DB_USERNAME: "laravel"
  DB_PASSWORD: "laravel"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel-local
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_DATABASE: "laravel"
  MYSQL_USER: "laravel"
  MYSQL_PASSWORD: "laravel"
