---
# Shared database credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: zuus
type: Opaque
stringData:
  root-password: "CHANGE_ME_ROOT"
  password: "CHANGE_ME_ZUUS"

---
# zuus-business application secrets
apiVersion: v1
kind: Secret
metadata:
  name: business-secrets
  namespace: zuus
type: Opaque
stringData:
  APP_KEY: "base64:CHANGE_ME_RUN_php_artisan_key_generate"
  DB_PASSWORD: "CHANGE_ME_ZUUS"
  REDIS_PASSWORD: "null"

---
# zuus-commerce application secrets
apiVersion: v1
kind: Secret
metadata:
  name: commerce-secrets
  namespace: zuus
type: Opaque
stringData:
  APP_KEY: "base64:CHANGE_ME_RUN_php_artisan_key_generate"
  CENTRAL_DB_PASSWORD: "CHANGE_ME_ZUUS"
  TENANT_TEMPLATE_DB_PASSWORD: "CHANGE_ME_ZUUS"
  REDIS_PASSWORD: "null"
  ZUUS_BUSINESS_STAFF_API_TOKEN: "CHANGE_ME"
